services:
  backend:
    image: clue-backend:1.0.0
    container_name: clue-backend
    restart: unless-stopped
    env_file:
      - ./backend.env
    volumes:
      - /data1/qwen2v/pic:/app/pic
      - /data1/qwen2v/road_property_rightsmodel/clue_ui_sandbox/backend/app:/app/app
    ports:
      - "6587:8000"

  frontend:
    image: clue-frontend:1.0.0
    container_name: clue-frontend
    restart: unless-stopped
    depends_on:
      - backend
    volumes:
      - /data1/qwen2v/road_property_rightsmodel/clue_ui_sandbox/frontend/dist:/usr/share/nginx/html
    ports:
      - "6586:80"




