version: '3'

services:
  debris-detector:
    image: htc/highway_property:250606   # 已导入的镜像名
    container_name: debris-detector
    ports:
      - "5000:5000"     # 主机端口:容器端口 开启托管本地图片到网络模块，使用端口映射
    volumes:
      - /data1/qwen2v/result.csv:/app/result.csv        # 挂载宿主机的 result.csv 文件（改成你机器上的实际路径）
      - /data1/qwen2v/road_property_rightsmodel:/app/road_property_rightsmodel   # 挂载宿主机代码目录（改成你机器上的实际路径）
      - /data1/qwen2v/pic:/app/pic
      - /data1/qwen2v/road_property_rightsmodel/data:/app/road_property_rightsmodel/data
      - /data1/qwen2v/wjr_test/screenshots:/app/screenshots
      - /data1/qwen2v/wjr_test/切片:/app/qiepian

    environment:
      - TZ=Asia/Shanghai    # 设置时区
    restart: unless-stopped
    networks:
      - htc-qwen2vl-network

networks:
  htc-qwen2vl-network:
    external: true